language : android

jdk:
- openjdk8

sudo: required

APP_ABI = armeabi-v7a arm64-v8a x86 x86_64

before_script:
- echo no | android create avd --force -n test -t android-26 --abi $APP_ABI
- emulator -avd test -no-skin -no-audio -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &

android:
  components:
  # Update Android SDK Tools
  - tools

  - build-tools-27.0.3
  - android-28

  # Support library
  - extra-android-support
  - extra-android-m2repository

notifications:
    email: true

before_install:
- chmod +x gradlew
