language : android

jdk:
- openjdk8

sudo: required

env:
  global:
  - ANDROID_API_LEVEL=29  # Compile SDK version
  - ANDROID_EMU_API_LEVEL=22
  - ANDROID_BUILD_TOOLS_VERSION=29.0.3
  - ANDROID_ABI=armeabi-v7a

android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - android-$ANDROID_API_LEVEL
  - android-$ANDROID_EMU_API_LEVEL
  - extra-android-support
  - sys-img-$ANDROID_ABI-google_apis-$ANDROID_EMU_API_LEVEL

licenses:
- '.+'

before_script:
- echo no | android create avd --force -n test -t android-$ANDROID_EMU_API_LEVEL --abi google_apis/$ANDROID_ABI
- emulator -avd test -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &

dist: trusty

script:
- ./gradlew assembleRelease
- ./gradlew clean test
- ./gradlew build